set_property SRC_FILE_INFO {cfile:D:/MyCode/MyFpga/MyXilinxVivado/uart_tx_multibyte/uart_tx_multibyte.srcs/constrs_1/new/uart_tx_multibyte_test.xdc rfile:../../../uart_tx_multibyte.srcs/constrs_1/new/uart_tx_multibyte_test.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports uart_tx]
